management:
#  endpoint:
#    beans:
#      enabled: true
  endpoints:
#    enabled-by-default: false
    web:
      exposure:
        include: '*'

mybatis:
  mapper-locations: classpath*:mapper/*.xml

server:
  port: 8082

swagger:
  enable: true
  base-package: xyz.hellothomas.jedi.admin.api
  title: Jedi-Admin-Service
  host: 127.0.0.1:8082
  description: Jedi-Admin服务
  version: 1.0.0
  contact:
    name: Thomas
    url: https://www.hellothomas.com
    email: tyty2017@qq.com

spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/my_monitor?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true
      &serverTimezone=Asia/Shanghai
    username: root
    password: 222222

admin-service:
  aspect.logging.enable: true