management:
#  endpoint:
#    beans:
#      enabled: true
  endpoints:
#    enabled-by-default: false
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
      probes:
        enabled: true
      group:
        readiness:
          include: readinessState,db

mybatis:
  mapper-locations: classpath*:mapper/config/*.xml

server:
  port: 8081

swagger:
  enable: true
  base-package: xyz.hellothomas.jedi.config.api
  title: Jedi-Config-Service
  host: 127.0.0.1:8081
  description: Jedi-Config服务
  version: 1.0.0
  contact:
    name: Thomas
    url: https://www.hellothomas.xyz
    email: tyty2017@qq.com

spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/jedi_config?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true
      &serverTimezone=Asia/Shanghai
    username: root
    password: 123456

config-service:
  cache-enabled: true
  collector-url: http://127.0.0.1:8080
  aspect.logging.enable: true

logging:
  level:
    xyz:
      hellothomas.jedi.config: debug