CREATE TABLE JEDI_TASK_EXECUTION (
  ID VARCHAR2(36 char) NOT NULL PRIMARY KEY,
  NAMESPACE_NAME VARCHAR2(32 char) NOT NULL,
  APP_ID VARCHAR2(32 char) NOT NULL,
  EXECUTOR_NAME VARCHAR2(64 char) NOT NULL,
  TASK_NAME VARCHAR2(64 char) NOT NULL,
  TASK_EXTRA_DATA VARCHAR2(1024 char),
  CREATE_TIME TIMESTAMP(3) NOT NULL,
  START_TIME TIMESTAMP(3),
  END_TIME TIMESTAMP(3),
  STATUS NUMBER(3,0) DEFAULT 0 NOT NULL,
  EXIT_CODE VARCHAR2(7 char),
  EXIT_MESSAGE VARCHAR2(1024 char),
  BEAN_NAME VARCHAR2(64 char) NOT NULL,
  BEAN_TYPE_NAME VARCHAR2(512 char) NOT NULL,
  METHOD_NAME VARCHAR2(64 char) NOT NULL,
  METHOD_PARAM_TYPES VARCHAR2(1024 char),
  METHOD_ARGUMENTS VARCHAR2(4000 char),
  RECOVERABLE NUMBER(1,0) DEFAULT 0 NOT NULL,
  RECOVERED NUMBER(1,0) DEFAULT 0 NOT NULL,
  HOST VARCHAR2(15 char) NOT NULL,
  TRACE_ID VARCHAR2(32 char),
  BY_RETRYER NUMBER(1,0) DEFAULT 0 NOT NULL,
  PREVIOUS_ID VARCHAR2(36 char),
  DATA_SOURCE_NAME VARCHAR2(64 char),
  LAST_UPDATED_USER VARCHAR2(32 char),
  LAST_UPDATED_TIME TIMESTAMP(3) DEFAULT CURRENT_TIMESTAMP(3) NOT NULL
);
COMMENT ON TABLE JEDI_TASK_EXECUTION IS '任务执行表';
COMMENT ON COLUMN JEDI_TASK_EXECUTION.NAMESPACE_NAME IS 'id';
COMMENT ON COLUMN JEDI_TASK_EXECUTION.NAMESPACE_NAME IS 'namespaceName';
COMMENT ON COLUMN JEDI_TASK_EXECUTION.APP_ID IS 'appId';
COMMENT ON COLUMN JEDI_TASK_EXECUTION.EXECUTOR_NAME IS 'executorName';
COMMENT ON COLUMN JEDI_TASK_EXECUTION.TASK_NAME IS 'taskName';
COMMENT ON COLUMN JEDI_TASK_EXECUTION.TASK_EXTRA_DATA IS 'taskExtraData';
COMMENT ON COLUMN JEDI_TASK_EXECUTION.CREATE_TIME IS 'createTime';
COMMENT ON COLUMN JEDI_TASK_EXECUTION.START_TIME IS 'startTime';
COMMENT ON COLUMN JEDI_TASK_EXECUTION.END_TIME IS 'endTime';
COMMENT ON COLUMN JEDI_TASK_EXECUTION.STATUS IS '0:registered, 1:doing, 2:success, 3:fail, 4:rejected';
COMMENT ON COLUMN JEDI_TASK_EXECUTION.EXIT_CODE IS 'exitCode';
COMMENT ON COLUMN JEDI_TASK_EXECUTION.EXIT_MESSAGE IS 'exitMessage';
COMMENT ON COLUMN JEDI_TASK_EXECUTION.BEAN_NAME IS 'beanName';
COMMENT ON COLUMN JEDI_TASK_EXECUTION.BEAN_TYPE_NAME IS 'beanTypeName';
COMMENT ON COLUMN JEDI_TASK_EXECUTION.METHOD_NAME IS 'methodName';
COMMENT ON COLUMN JEDI_TASK_EXECUTION.METHOD_PARAM_TYPES IS 'methodParamTypes';
COMMENT ON COLUMN JEDI_TASK_EXECUTION.METHOD_ARGUMENTS IS 'methodArguments';
COMMENT ON COLUMN JEDI_TASK_EXECUTION.RECOVERABLE IS 'recoverable';
COMMENT ON COLUMN JEDI_TASK_EXECUTION.RECOVERED IS 'recovered';
COMMENT ON COLUMN JEDI_TASK_EXECUTION.HOST IS 'host';
COMMENT ON COLUMN JEDI_TASK_EXECUTION.TRACE_ID IS 'traceId';
COMMENT ON COLUMN JEDI_TASK_EXECUTION.BY_RETRYER IS 'byRetryer';
COMMENT ON COLUMN JEDI_TASK_EXECUTION.PREVIOUS_ID IS 'previousId';
COMMENT ON COLUMN JEDI_TASK_EXECUTION.DATA_SOURCE_NAME IS 'dataSourceName';
COMMENT ON COLUMN JEDI_TASK_EXECUTION.LAST_UPDATED_USER IS 'lastUpdatedUser';
COMMENT ON COLUMN JEDI_TASK_EXECUTION.LAST_UPDATED_TIME IS 'lastUpdatedTime';
CREATE INDEX JEDI_TASK_EXECUTION_IDX_1 ON JEDI_TASK_EXECUTION(NAMESPACE_NAME, APP_ID, EXECUTOR_NAME, TASK_NAME, STATUS);
CREATE INDEX JEDI_TASK_EXECUTION_IDX_2 ON JEDI_TASK_EXECUTION(LAST_UPDATED_TIME);
