CREATE TABLE IF NOT EXISTS `JEDI_TASK_EXECUTION` (
  `ID` varchar(36) NOT NULL COMMENT 'id',
  `NAMESPACE_NAME` varchar(32) NOT NULL COMMENT 'namespaceName',
  `APP_ID` varchar(32) NOT NULL COMMENT 'appId',
  `EXECUTOR_NAME` varchar(64) NOT NULL COMMENT 'executorName',
  `TASK_NAME` varchar(64) NOT NULL COMMENT 'taskName',
  `CREATE_TIME` timestamp(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) COMMENT 'createTime',
  `START_TIME` timestamp(3) COMMENT 'startTime',
  `END_TIME` timestamp(3) COMMENT 'endTime',
  `STATUS` tinyint(4) unsigned NOT NULL DEFAULT 0 COMMENT '0: created, 1: success, 2: fail',
  `EXIT_CODE` varchar(7) COMMENT 'exitCode',
  `EXIT_MESSAGE` varchar(1024) COMMENT 'exitMessage',
  `BEAN_NAME` varchar(64) NOT NULL COMMENT 'beanName',
  `BEAN_TYPE_NAME` varchar(512) NOT NULL COMMENT 'beanTypeName',
  `METHOD_NAME` varchar(64) NOT NULL COMMENT 'methodName',
  `METHOD_ARGUMENTS` varchar(4000) COMMENT 'methodArguments',
  `TRACE_ID` char(32) COMMENT 'traceId',
  `PREVIOUS_ID` char(36) COMMENT 'previousId',
  `DATA_SOURCE_NAME` char(64) COMMENT 'dataSourceName',
  `LAST_UPDATED` timestamp(3) NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3) COMMENT 'lastUpdated',
  PRIMARY KEY (`ID`),
  KEY `IDX_taskName` (`NAMESPACE_NAME`,`APP_ID`,`EXECUTOR_NAME`, `TASK_NAME`, `STATUS`),
  KEY `IDX_lastUpdated` (`LAST_UPDATED`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='任务执行表';
